### ISSUE TITLE
官网demo无法打开了

### ISSUE THREAD

**Issue by pizberg** [Zhaocl1997/walnut-admin-client#1]

**Comment by Zhaocl1997** [comment]
有时候确实会有白页，刷新一下或者清一下localstorage试试，原因应该是持久化的部分报错了，最新有点忙，后续会修复 + 持续更新的

**Comment by pizberg** [comment]
谢谢
{"data":null,"code":4040,"msg":"Endpoint doesn't exist"}

**Comment by Zhaocl1997** [comment]
哪个接口？不应该啊

**Comment by pizberg** [comment]
就是https://walnut-admin-doc.netlify.app/首页的“在线预览”

**Comment by pizberg** [comment]
能开放个预览账号吗。谢谢

**Comment by Zhaocl1997** [comment]
先用这个吧，账号：admin，密码：2020。增删改的接口暂时都在前端拦截住了。

**Comment by pizberg** [comment]
很赞！

**Comment by Zhaocl1997** [comment]
感谢关注
