### ISSUE TITLE
密码是啥

### ISSUE THREAD

**Issue by a552422934** [Zhaocl1997/walnut-admin-client#2]
重新做了登录页面，支持账号登录、短信登陆和二维码登录（当然只是个模板，目前只有账号登陆能用）

**Comment by Zhaocl1997** [comment]
感谢关注，今晚到家会部署一下正式环境，届时会有提示的体验账号密码

**Comment by Zhaocl1997** [comment]
昨晚已重新发版，有提示的账号密码

**Comment by a552422934** [comment]
谢谢,但是我感觉项目太复杂了,自己用不上
